### ISSUE TITLE
Renaming produces TypeError: t.toLowerCase is not a function

### ISSUE THREAD

**Issue by grantx2016** [pjeby/tag-wrangler#51] opened 2022-10-05 00:55 UTC
I am frequently encountering the following error when renaming tags:

`error: TypeError: t.toLowerCase is not a function`

![Obsidian--Tag Wranglr--TypeError--Issue-2022-10-05](https://user-images.githubusercontent.com/19563571/193956394-aeb7682e-0d69-42bc-baf7-2a36be5b0cc4.png)

For example, this error occurred when trying to rename "amex" to "30-org/amex".

My environment:
Obsidian: v0.15.9
Tag Wrangler: 0.5.3
OS: macOS Monterey v12.6

**Comment by pjeby** [comment] 2022-10-05 04:06
Can you paste the full error from the development console?  Thanks.

**Comment by grantx2016** [comment] 2022-10-09 03:30
plugin:tag-wrangler:7677 TypeError: t.toLowerCase is not a function
    at eval (plugin:tag-wrangler:529:30)
    at Array.map (<anonymous>)
    at Replacement.inArray (plugin:tag-wrangler:518:25)
    at processField (plugin:tag-wrangler:7309:25)
    at File.replaceInFrontMatter (plugin:tag-wrangler:7317:17)
    at File.renamed (plugin:tag-wrangler:7268:25)
    at async eval (plugin:tag-wrangler:7354:13)
    at async Progress.forEach (plugin:tag-wrangler:428:17)
    at async renameTag (plugin:tag-wrangler:7352:5)
    at async TagWrangler.rename (plugin:tag-wrangler:7676:15)
rename @ plugin:tag-wrangler:7677

**Comment by pjeby** [comment] 2022-10-09 05:53
It looks like you have a note with front matter for the `tag` or `tags` field that is not a string.  Can you identify the specific note at issue, then paste the front matter here inside a `yaml` block?  That is, you would put something like this into the comment here:

~~~markdown
```yaml
---
# front matter goes here
Some-Field: value
Another-field: whatever
# and so on
---
```
~~~

Be sure to use three backquotes (aka grave accent characters) both on the start line and the end line.  Thanks.

**Comment by pjeby** [comment] 2022-10-10 12:25
The issue is that `- 2016` and similar tags are being interpreted as numbers by YAML, and Tag Wrangler expects strings.  If a tag is just a number with no other punctuation, it needs to be enclosed in quote marks to be treated as a string.

**Comment by grantx2016** [comment] 2022-10-10 21:55
Interesting. Thanks for the advice. I would never have realised that.

**Comment by bradsayers** [comment] 2023-09-18 16:06
I'm getting this error when trying to rename a tag by right clicking and choosing rename. I have 74 notes with a tag called dreams that I would like to rename to dream. How can I do this?

**Comment by pjeby** [comment] 2023-09-18 18:38
Make sure you don't have any front matter `tags` or `tag` fields that contain a number that's not in quotes, or an empty (null) field.

**Comment by bradsayers** [comment] 2023-09-18 19:27
What would be the easiest and quickest way to see and fix that in 74 notes?

**Comment by pjeby** [comment] 2023-09-19 05:33
What you're looking for would appear something like this:

```yaml
# These are all tags that will break:
Tags: [ true, false, null, 27 ]
```

Or this:

```yaml
Tags:
  - true
  - false
  - null
  - 27
```

Basically, if you have *any* tags without single or double quotes around them, they will cause problems, especially if they are a reserved word (true, false, null) or a number.

I've gone ahead and created a fix for this issue, though, so if you update Tag Wrangler to 0.5.13 you should be able to rename without this issue.  Your tags, however, *will still be corrupt* and when you start using the new properties editor of Obsidian 1.4 you may lose data if you don't find and quote the tags in question.  So you will want to review the contents of your tag fields to find the issue.  Basically, just make sure all your tag names are quoted and in one of the correct YAML list formats (indented `-` list or inline `[ ]` list).

**Closed** 2023-09-19 05:35 UTC

**Comment by bradsayers** [comment] 2023-09-19 12:25
@pjeby Thanks so much for the insight on the behavior and especially for the fix! The updated plugin fixed my immediate problem, and next I will address the tag issue in the YAML. I think this would have happened when I used Joplin to migrate Evernote into Obsidian.
