### ISSUE TITLE
Did Obsidian v1.2 break tagwrangler?

### ISSUE THREAD

**Issue by jebeaudoin** [pjeby/tag-wrangler#78] opened 2023-03-29 18:38 UTC
Maybe it is a coincidence, but tagwrangler isn't working for me today. I notice Obsidian v1.2 was just pushed and chatter in Discord suggests several plugins have been broken (Licat: "There was some internal changes to the tree view data structures to unify the internal APIs so shared behaviors can work better All of these broken plugins currently hook deep into internal data structures which were switched around.")

**Comment by pjeby** [comment] 2023-03-30 00:25
Can you provide a link to the discussion?  Thanks.

**Comment by jebeaudoin** [comment] 2023-03-30 00:49
Not a regular discord user but I think I have the message link: https://discord.com/channels/686053708261228577/716028884885307432/1090685827996188863

**Comment by pjeby** [comment] 2023-03-30 02:32
Thanks, the issue is now fixed in 0.3.16 - at least the problems I was able to identify myself.

**Comment by pjeby** [comment] 2023-03-30 02:33
Whoops, I mean 0.5.8 - 0.3.16 is the Hotkey Helper fix for 1.2  😁

**Comment by jebeaudoin** [comment] 2023-03-30 11:09
Thanks! Working on my vault again!

**Closed** 2023-03-30 11:09 UTC
