### ISSUE TITLE
Renaming tag does not rename tag in blocks

### ISSUE THREAD

**Issue by cyc115** [pjeby/tag-wrangler#62] opened 2022-12-03 19:01 UTC
Tags referenced within blocks requires manual renaming upon renaming in the tag pan. 
  \`\`\`dataview
  TASK from ""
  where 
  contains(tags, "TagName")
  and !completed
  \`\`\`

**Comment by pjeby** [comment] 2022-12-03 20:56
This is a duplicate of issues #20,  #24, and #52 - please search for existing issues before opening new ones.  Thanks.

**Closed by pjeby** 2022-12-03 20:56 UTC
