### ISSUE TITLE
Feature request: Search #searched-tag from list to tags to filter it out

### ISSUE THREAD

**Issue by bhickta** [pjeby/tag-wrangler#21] opened 2021-07-14 03:33 UTC
* Great plugin
* It would be nice to have a search functionality in tag-wangler plugin, which could search tag by its name
* Eg
 * From all the list of tags, we could search #searched-tag to filter it out from the whole list

**Comment by pjeby** [comment] 2021-07-14 05:28
Closing as a duplicate of #16

**Closed by pjeby** 2021-07-14 05:28 UTC
