### ISSUE TITLE
Search for tags (Filter based on keyword)

### ISSUE THREAD

**Issue by tonyxiao** [pjeby/tag-wrangler#58] opened 2022-11-03 13:02 UTC
I was looking for a way to filter the list of tags I have in a quick way in the tag pane, and found this plugin. But it seems that it isn't possible? Whereas the "search for tags" is just searching for notes containing tags?

**Comment by pjeby** [comment] 2022-11-03 19:01
This is a duplicate of issue #35 - please search for existing issues before creating new ones.  Thanks.

**Closed by pjeby** 2022-11-03 19:01 UTC
