### ISSUE TITLE
Feature request:  delete tags

### ISSUE THREAD

**Issue by wealthychef1** [pjeby/tag-wrangler#57] opened 2022-11-02 17:48 UTC
In addition to renaming tags, I'd love to be able to delete all instances of a tag in my vault.  Thank you

**Comment by pjeby** [comment] 2022-11-02 20:56
This is a duplicate of #4 - please search existing issues before creating new ones.  Thanks.

**Closed by pjeby** 2022-11-02 20:56 UTC

**Comment by wealthychef1** [comment] 2022-11-02 23:16
OK, great, although I would just say that your solution of renaming the tags then hunting them down one by one is one you could replicate in your plugin... just rename the tag, surrounding it with a magic cookie like "DELETETAG_DELETETAG_RANDOM32BITCHARSTRING", which is an operation that you already accept as non-destructive,.  After renaming, then you can just look for these special tags which are guaranteed to be unique and delete them.  Not risky at all.

**Comment by pjeby** [comment] 2022-11-02 23:30
Please put all discussion on issue #4, not here, at least if you want a reply.
