### ISSUE TITLE
Rename Tag Error — "TypeError: a.split is not a function"

### ISSUE THREAD

**Issue by OldSoul-io** [pjeby/tag-wrangler#68] opened 2023-01-08 23:29 UTC
**Thanks for the beautiful Tag Wrangler plugin and all of your hard work on it!**

 I tried to rename my #task tag to a #TODO tag for various reasons today:
<img width="424" alt="CleanShot 2023-01-08 at 17 45 44@2x" src="https://user-images.githubusercontent.com/15693988/211223377-4a6eb855-5500-4e07-94d4-5c3a7c8863d9.png">

Unfortunately, this effort returned a _TypeError_ saying, "_a.split is not a function_."
<img width="424" alt="CleanShot 2023-01-08 at 17 46 11@2x" src="https://user-images.githubusercontent.com/15693988/211223382-a4119452-7e4f-40fa-bb3e-eed019c96143.png">

Being the quasi-hacker-wannabe that I am, I tried looking up the error and found [a good explanation](https://itsjavascript.com/javascript-typeerror-string-split-is-not-a-function) of the error in general. But after losing an hour wandering through the source code admiring the work instead, I figure I should file an Issue and step away before my ADHD makes me hyperfocus on it (when I honestly don't have time to figure it out, and you should be the one to know about it in the first place). 

I hope the screenshots and description help. Let me know if I can provide further context or if the problem lies between my keyboard and the chair.

**Comment by pjeby** [comment] 2023-01-09 05:13
Do you have any tags that are a plain number with no non-numeric characters?  Are any of them in an unquoted item in a note's metadata (that also has the `#task` tag)?  If so, please share the metadata here (inside a triple-backquote code block).

**Comment by oldsoul-ja** [comment] 2023-01-13 19:09
I did have some accidental tags that were created from CSS colors, like:
```
.st-dark-gray {  
    color: #425466;  
}, 
```
I remedied this by putting said CSS within proper code blocks so that it doesn't mistake them for tags, but those were never in my note's metadata.

I'm not sure if this is related or a possible issue, but I have some #task tags whose line item is nothing but an internal wiki link, like:

```- [ ] #task [[Internal Page Link Here]]```

**Comment by pjeby** [comment] 2023-01-13 20:14
Do you have any notes with an empty Tag or Tags field, then?  Or one with `null`?

**Comment by oldsoul-ja** [comment] 2023-01-13 22:43
**Success!** That appears to have been the root cause: I had one template where the tag metadata was left empty by mistake. I updated that field, and everything flowed through successfully as expected. 

If that is not expected behavior or a commonly known limitation, perhaps it could be noted somewhere for reference if others run across this error. I'd have never figured that out on my own (and I'm not even sure how I would search for an empty tag, but I immediately suspected my templates were the most probable culprit). 

Thanks so much for your help!! You rock.
Keep up the awesome work and I hope you have a wonderful weekend!

**Comment by pjeby** [comment] 2023-01-13 23:38
This was not a known issue; the numbered tags were, but in any case I intend to fix both, I just wanted to confirm the issue.

**Comment by pjeby** [comment] 2023-10-16 04:15
This issue should now be fixed as of Tag Wrangler 0.5.13, released last month.

**Closed by pjeby** 2023-10-16 04:15 UTC
