### ISSUE TITLE
Fails to load under Obsidian 1.2.7 on Mac

### ISSUE THREAD

**Issue by InvaderJ** [pjeby/tag-wrangler#83] opened 2023-05-03 01:20 UTC
Title, sorry I can't provide robust detail, am working late. -_- Obsidian reports "failed to load plugin text-wrangler" under Obsidian 1.2.7, released today.

**Comment by pjeby** [comment] 2023-05-03 01:46
Have you updated Tag Wrangler?  Obsidian 1.2.x requires Tag Wrangler 0.5.8.

**Comment by InvaderJ** [comment] 2023-05-03 02:16
Ah hmm, quite odd odd, looking more closely, it does seem that Tag Wrangler has loaded, and yet Obsidian is consistently saying that it has failed to load on every launch. Let me know if there is any debug info I can provide… otherwise perhaps this is some weird glitch. [Shot here](https://share.ux.fyi/hGjt1Qev)

**Comment by pjeby** [comment] 2023-05-03 03:11
So, you didn't say if you updated to 0.5.8?

**Comment by theSmokingFrog** [comment] 2023-05-03 12:28
After updating Obsidian to 1.2.7 on macOS 12.6, I got the exact same error with the plugin on version 0.5.8.

Unfortunately I'm not able to reproduce it but at least I can confirm that I've seen the issue too.

**Comment by pjeby** [comment] 2023-05-03 18:35
Ok, well, anyone who can reproduce the problem, please check the inspector panel (ctrl/cmd + shift + i) and see if there are any errors shown in the console and if so provide them here.  I have never seen this problem with TW 0.5.8 and Obsidian 1.2.x (including 1.2.7) on Windows, and I don't have a Mac I can test this on.

**Comment by rhhub** [comment] 2023-05-07 17:52
Mine doesn't load in windows 10 or iphone 12

Windows 10:
![image](https://user-images.githubusercontent.com/7444613/236694108-ff81fcc2-eba5-45ba-9c96-752979c2cf7a.png)

**Comment by rhhub** [comment] 2023-05-07 18:06
iphone 12 ![image](https://user-images.githubusercontent.com/7444613/236694823-aa4ccb8c-7bd4-4577-bf22-159857101537.png)

**Comment by pjeby** [comment] 2023-05-07 19:41
So, here are the steps to investigate, since I cannot repro this on Windows:

1. Open the developer console (Cmd-Shift-I on Mac, Ctrl-Shift-I on Windows)
2. Check for any error messages and report them here
3. With the console still open, go to community plugins, and manually disable Tag Wrangler, then re-enable it.  Do any error messages appear in the console?  (If so, report them here.) Does the plugin load?
4. Open the sandbox vault (F1 or the Help button, then click the "Open" button next to "Sandbox Vault").
5. Open the developer console in the sandbox vault
6. Go to community plugins, install and enable Tag Wrangler.  Report any error messages that appear in the console, and whether or not the plugin activated.

Following this procedure and reporting all the results here is the only way I can find out what is actually going on and try to fix it.  Thanks.

**Comment by rhhub** [comment] 2023-05-07 20:08
I went through the steps. It's all silent. Everything is the same as the picture 3 posts ago. Sorry I can't be of more help. I just wanted to suggest it's not platform specific. It might be hardware specific.

**Comment by pjeby** [comment] 2023-05-07 22:49
@rhhub I'm confused: if it's "all silent" then how is there a problem?  Is the core tag plugin enabled?  Is the tag pane open in the workspace?  I'm also confused by your screenshots that look like you're looking for commands installed by Tag Wrangler. Tag Wrangler doesn't *have* any commands.  The way you use Tag Wrangler is with menu operations on the built-in Obsidian tag pane (or on tags in notes).  There are no hotkeys, commands, or settings, so the only way you will know if TW is active and functional is by right-clicking a tag in the tag page to see if you get the TW menu items.  If the tag pane isn't visible in your workspace, you need to run the Obsidian "Show Tags" command.  Then you'll be able to right-click or long-press tags to perform Tag Wrangler operations.

**Comment by rhhub** [comment] 2023-05-07 23:04
@pjeby I am terribly sorry. I re-enabled core tags and it works. It worked for months. I must of disabled it when working with load times.

**Comment by pjeby** [comment] 2023-05-07 23:49
Ok, can everyone else (i.e. @InvaderJ and @theSmokingFrog) confirm whether they have the core tag plugin enabled and the tag pane visible, and whether Tag Wrangler 1) actually works, and 2) displays an error message either at startup or when manually toggled on and off?  If it's working for everybody and there are no more error messages we can close this, but if it's not working and/or it displays error messages then I'll need some more information to investigate further.

**Comment by theSmokingFrog** [comment] 2023-05-08 07:51
By now I dedicated quite some time to reproduce the error - but since the initial posting I was not able to do so.
1. The plugins "Tags" and "Tag Wrangler" are both activated
2. Not even disabled the Core-"Tags" Plugin ended up producing the same behaviour

I saw this issue after the Update to Obsidian 1.2.7 with 0.5.8 of Tag Wrangler already installed. It was consistent on reload BUT since restarting Obsidian never occurred to me again. Maybe something inside of Obsidian had hiccups after the update? Who knows.

From my point of view there is no need in investigating further :)

**Closed** 2023-05-08 13:45 UTC
