### ISSUE TITLE
delete a tag ?

### ISSUE THREAD

**Issue by sky31even** [pjeby/tag-wrangler#27] opened 2021-08-20 01:13 UTC
would you consider adding a function which allows us to delete a specific tag from the file~

it'd be better if we could choose the behavior since someone add tags independently at the start / end of the text and others, add into the content.

for previous ones, we could delete the tags from the file and for the latter ones , we could choose to delete the symbol of the tags in the content only. ~~

**Comment by pjeby** [comment] 2021-08-20 02:56
Duplicate of #4 and #12

**Closed by pjeby** 2021-08-20 02:56 UTC
