### ISSUE TITLE
Tag deletion?

### ISSUE THREAD

**Issue by elight** [pjeby/tag-wrangler#47] opened 2022-06-15 17:21 UTC
Given that tag-wrangler can find each tag location, line by line, it would be **so handy** if I could right click and select to delete a tag. I often find that my tag choices are suboptimal. Sometimes, I want to rename. However, sometimes I just want to nuke the tag entirely.

Great plugin!

**Comment by pjeby** [comment] 2022-06-15 20:37
Closing as duplicate of issue #4.

**Closed by pjeby** 2022-06-15 20:37 UTC
