### ISSUE TITLE
Hope to add the function of deleting tag(s)~

### ISSUE THREAD

**Issue by qwepuorytgj** [pjeby/tag-wrangler#109] opened 2023-09-18 10:22 UTC
If there is a tag named A, it is marked in lots of notes, now I want to delete it. 
What I can do is to delete it from the notes one by one.

**Comment by pjeby** [comment] 2023-09-18 10:57
Duplicate of issue #4 - please see there for discussion

**Closed by pjeby** 2023-09-18 10:57 UTC
