### ISSUE TITLE
Add Tags to Select Notes

### ISSUE THREAD

**Issue by dogwaddle** [pjeby/tag-wrangler#22] opened 2021-07-16 22:13 UTC
Awesome plug in. An additional feature that would be nice is the ability to add a tag to all notes or select group of notes. For example I'd like to add the #Map tag to all my notes, than remove the tag from the notes that act as big link blobs in graph view. This can make graph view more interesting with a very large note set.

**Comment by pjeby** [comment] 2021-07-16 23:11
Closing as a duplicate of #8

**Closed by pjeby** 2021-07-16 23:11 UTC
