### ISSUE TITLE
Failed to enable plugin in 1.0

### ISSUE THREAD

**Issue by StevenGann** [pjeby/tag-wrangler#61] opened 2022-11-15 21:39 UTC
**Describe the bug**
On startup Obsidian does not enable this plugin. Manually enabling on the list of installed plugins fails and shows a "Failed to enable plugin" toast. Going into the Community Plugin list and pressing the enable button there causes the same error, but the plugin enables and functions correctly despite the error.

**To Reproduce**
1. Install the latest Obsidian (1.0.3) on Windows or Linux
2. Install the latest version of this plugin
3. Attempt to enable the plugin
4. See error in console

```
app.js:1 Plugin failure: tag-wrangler DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at r4.<anonymous> (app://obsidian.md/app.js:1:1032505)
    at app://obsidian.md/app.js:1:235201
    at Object.next (app://obsidian.md/app.js:1:235306)
    at a (app://obsidian.md/app.js:1:234045)
```

**Expected behavior**
I expect the plugin to be enabled on startup.

**Environment:**
 - OS: Windows and Linux.
 - Obsidian Version: 1.0.3

**Comment by pjeby** [comment] 2022-11-15 23:21
Can you reproduce this in the sandbox with no other plugins active? (With the tags plugin enabled, of course.)

**Comment by snippet-container** [comment] 2022-12-26 21:05
I had the same issue, could not enable the plugin after installing it.
I tried it in the sandbox, with no other plugins installed, and it worked,
Then, in the "productive" vault, i disabled the tag-pane and re-enabled it. Worked like a charm.
Probably worth to be mentioned: I had moved the tag-pane to the left side, before I tried to install and activate the plugin. After re-enabling it, it was located at its standard location.

**Comment by pjeby** [comment] 2022-12-26 21:38
I don't suppose you could paste the full error message here?

**Comment by snippet-container** [comment] 2022-12-27 00:04
Sorry, I just saw the "Failed to enable plugin" message, like mentioned by @StevenGann.
I did not check anything other, just disabled and enabled the tag-pane.

**Comment by pjeby** [comment] 2023-04-03 22:54
Closing since AFAIK the plugin is working correctly even in 1.2.

**Closed by pjeby** 2023-04-03 22:54 UTC
