### ISSUE TITLE
Can’t find pages linked to the tag in the tag page

### ISSUE THREAD

**Issue by mayscu** [pjeby/tag-wrangler#74] opened 2023-03-09 01:19 UTC
Hi. I have installed the plugin and find the tag page function is super usably. But i have found that the pages with the tag can’t emerge in the “mention” panel which is different from the document. So i am wondering if there is some conflicts between the tag wrangler and other plugins such as the influx.

**Comment by mayscu** [comment] 2023-03-09 04:56
thanks for the reply. Sorry for not explaining it clearly. 
in the document, there goes “ In the meantime, however, you can use Obsidian's backlinks to find and change such references from the tag page. Specifically, viewing a tag page's "unlinked mentions" will show you all the locations where the tag was used and "link" buttons you can use to convert them to page links. ” . But i can’t find those pages which are related to the tag in the unlinked mentions part. For example, i already have many pages with the tag #book, and i created a tag page for #book. However, in this tag page’s unlinked mentions, I can’t find anything and it is empty.
As for the influx, it the name of another plugin. I mentioned it just for a example. For i have tried switch off it and the problem persists, it may be not important for this issue.

**Comment by pjeby** [comment] 2023-03-09 07:20
Something must have changed in Obsidian then; it works in versions 1.1.10 and lower.  You might try downgrading your Obsidian version to confirm.  (Unless you are on 1.1.10 or lower, in which case something else is going on.)

**Comment by pjeby** [comment] 2023-04-17 18:24
I'm not able to reproduce this problem on Obsidain 1.1.16; are you still having it?

**Comment by puertoric** [comment] 2023-04-21 17:38
Looking for exactly this issue I stumbled about this thread. I have the same issue. I've created a tag page, but I don't see the mentioned list of pages in die unlinked section. I'm using Obsidian version 1.2.0.

**Comment by pjeby** [comment] 2023-04-21 20:28
Have you *clicked* on the unlinked section to expand it?  It's not at all obvious in the new default theme whether the mentions are expanded or not.  If there is no number shown next to "Unlinked mentions", it isn't active: you have to click on it.  If there are genuinely no unlinked mentions found, there will be a zero there, rather than a blank space.

**Comment by pjeby** [comment] 2023-05-18 19:32
Closing since no-one responded to my last inquiry and AFAICT it works correctly when "unlinked mentions" is expanded.

**Closed by pjeby** 2023-05-18 19:32 UTC
